import type { Product } from './product.types';

export const products: Product[] = [
  {
    id: 1,
    title: 'هدفون بی سیم مدل WH-1000XM5',
    brand: 'Sony',
    image: '/images/products/shirt.webp',
    alt: 'هدفون بی سیم سونی',
    price: 835000,
    oldPrice: 940000,
    discount: 25,
    href: '/product/sony-wh-1000xm5',
  },
  {
    id: 2,
    title: 'عطر زنانه مدل Coco',
    brand: 'Chanel',
    image: '/images/products/shirt.webp',
    alt: 'عطر زنانه',
    price: 1250000,
    oldPrice: 1500000,
    discount: 15,
    href: '/product/coco',
  },
  {
    id: 3,
    title: 'کفش ورزشی مردانه',
    brand: 'Nike',
    image: '/images/products/shirt.webp',
    alt: 'کفش ورزشی مردانه',
    price: 1890000,
    oldPrice: 2200000,
    discount: 14,
    href: '/product/nike-sport',
    sizes: [
      { id: '42', label: '42', available: true },
      { id: '44', label: '44', available: false },
      { id: '46', label: '46', available: true },
      { id: '48', label: '48', available: false },
    ],
    colors: [
      { id: 'black', name: 'مشکی', hex: '#111827', available: false },
      { id: 'blue', name: 'آبی', hex: '#2563eb', available: true },
      { id: 'charcoal', name: 'زغالی', hex: '#374151', available: false },
    ],
  },
  {
    id: 4,
    title: 'عینک آفتابی Ray-Ban',
    brand: 'Ray-Ban',
    image: '/images/products/shirt.webp',
    alt: 'عینک آفتابی ری بن',
    price: 2100000,
    oldPrice: 2500000,
    discount: 16,
    href: '/product/rayban',
  },
  {
    id: 5,
    title: 'کوله پشتی لپ تاپ',
    brand: 'Koton',
    image: '/images/products/shirt.webp',
    alt: 'کوله پشتی',
    price: 980000,
    oldPrice: 1200000,
    discount: 18,
    href: '/product/backpack',
  },
  {
    id: 6,
    title: 'ساعت مچی مردانه',
    brand: 'Casio',
    image: '/images/products/shirt.webp',
    alt: 'ساعت مچی مردانه',
    price: 1750000,
    oldPrice: 2100000,
    discount: 17,
    href: '/product/casio-watch',
  },
];
