import type { Metadata } from 'next';
import './globals.css';
import './Vazirmatn-font-face.css';
import { cn } from '@/lib/utils';
import Navigation from '@/components/layout/Header/Navigation';

export const metadata: Metadata = {
  title: 'sky book',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={cn('h-full', 'antialiased', 'font-sans')}>
      <body className="min-h-full flex flex-col">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
