import type { Metadata } from 'next';
import './globals.css';
import './Vazirmatn-font-face.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={cn('h-full', 'antialiased', 'font-sans')}>
      <body className="min-h-full flex flex-col bg-[#f8fafc]">
        <header className="w-11/12 mx-auto bg-white h-20 rounded-lg shadow p-2 my-3">
          header
        </header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
