export const blogPosts = [
  {
    id: 1,
    title: 'راهنمای انتخاب لباس مناسب برای استایل شما',
    excerpt: 'با چند نکته ساده انتخاب لباس مناسب را راحت‌تر کنید.',
    image: '/images/blog/blog-2.webp',
    href: '/blog/clothing-guide',
    category: 'استایل و مد',
    readTime: '۵ دقیقه',
    views: 1248,
    likes: 86,
    publishedAt: '۱۲ مرداد ۱۴۰۵',
  },
  {
    id: 2,
    title: 'راهنمای انتخاب شلوار جین مناسب',
    excerpt: 'با انواع مدل‌های شلوار جین و تفاوت آن‌ها آشنا شوید.',
    image: '/images/blog/blog-1.webp',
    href: '/blog/jeans-guide',
    category: 'راهنمای خرید',
    readTime: '۷ دقیقه',
    views: 2156,
    likes: 143,
    publishedAt: '۹ مرداد ۱۴۰۵',
  },
  {
    id: 3,
    title: 'انواع پارچه، جنس و ویژگی‌های آن‌ها',
    excerpt: 'قبل از خرید لباس با جنس پارچه‌ها بیشتر آشنا شوید.',
    image: '/images/blog/blog-3.webp',
    href: '/blog/fabric-guide',
    category: 'پارچه و پوشاک',
    readTime: '۶ دقیقه',
    views: 987,
    likes: 64,
    publishedAt: '۵ مرداد ۱۴۰۵',
  },
] as const;
